import palette from 'google-palette';
const schemes  = [
        "tol",
        "tol-dv",
        "tol-sq",
        "tol-rainbow",
        "rainbow",
        "cb-YlGn",
        "cb-YlGnBu",
        "cb-GnBu",
        "cb-BuGn",
        "cb-PuBuGn",
        "cb-PuBu",
        "cb-BuPu",
        "cb-RdPu",
        "cb-PuRd",
        "cb-OrRd",
        "cb-YlOrRd",
        "cb-YlOrBr",
        "cb-Purples",
        "cb-Blues",
        "cb-Greens",
        "cb-Oranges",
        "cb-Reds",
        "cb-Greys",
        "cb-PuOr",
        "cb-BrBG",
        "cb-PRGn",
        "cb-PiYG",
        "cb-RdBu",
        "cb-RdGy",
        "cb-RdYlBu",
        "cb-Spectral",
        "cb-RdYlGn",
        "cb-Accent",
        "cb-Dark2",
        "cb-Paired",
        "cb-Pastel1",
        "cb-Pastel2",
        "cb-Set1",
        "cb-Set2",
        "cb-Set3",
        "sol-base",
        "sol-accent"];

        getRandomScheme = () =>{
            return schemes[Math.floor(Math.random() * schemes.length)+1];
        }
        export default getRandomScheme
